### ISSUE TITLE
Pattern matching error at old version.

### ISSUE THREAD

**Issue by laurent01-sw** [janestreet/core_kernel#106]
Hi, I need to build the version tagged by "111.25.00".
However, after type `make`, following error is occurred.

`
File "setup_dev.ml", line 8, characters 8-21:
Error: This pattern matches values of type 'a * 'b * 'c
       but a pattern was expected which matches values of type
         OASISTypes.common_section * OASISTypes.build_section *
         OASISTypes.library * OASISTypes.unix_dirname option
`

Here is my environment.
OS : Ubuntu 14.04
Ocaml Compiler Version : 4.02.0
OPAM Version : 1.2.0 (Repository seems to be redirected to 1.2.2)

I'm sorry to ask question about old version. Forgive me please. Thanks.

**Comment by bcc32** [comment]
Can you try an older version of oasis?  It appears that [this commit](https://github.com/ocaml/oasis/commit/90b8e3ee93535174fe882a61002153594464f865) changed the type of the `lib_hook` function, which is used in `setup.ml`.  The change appears in oasis-0.4.7, so oasis-0.4.6 or older should fix this particular error.

**Comment by laurent01-sw** [comment]
It works! Thanks!
