### ISSUE TITLE
Improve js_of_ocaml support

### ISSUE THREAD

**Issue by m2ym** [janestreet/core_kernel#13]
## Problems

I'm trying to use core_kernel together with js_of_ocaml, but currently
there are few issues.

1. Core_kernel requires 32bit compiler

    Although we should use 32bit compiler, OCaml's support for 32bit
    compiler on 64bit architecture is very poor.  I'm trying to add
    support for 32bit compiler on OSX, but it is a hard task to me.

2. Core_kernel includes unit tests in its implementation

    pa_ounit embeds unit tests as implementations so that unit tests
    can be ran from command-line with special argument
    `inline-test-runner`.  This is useful, but this also prevents
    js_of_ocaml from doing dead-code-elimination.  As a result,
    js_of_ocaml outputs a huge JavaScript even though a source code is
    tiny.

## Workaround

Here is an installation script of a customized core_kernel (named
core_kernel_js) that solves the issues above.

https://github.com/m2ym/core_kernel_js/blob/master/Makefile

What this script does are

* forcing 32bit architecture by replacing `ARCH_SIXTYFOUR`
* removing an assertion of arhictecture located at lib/pool.ml
* compiling with pseudo pa_ounit that never generate unit tests

## Result

By this workaround, the following program becomes runnable even on
64bit architecture, though it is risky.

    (* a.ml *)
    open Core_kernel.Std
    (* open Core_kernel_js.Std *)
    
    let () =
      let h = Int.Table.create ~size:32 () in
      for i = 1 to 100 do
        Hashtbl.set h i i
      done;
      Format.printf "%a@." Sexp.pp_hum (Int.Table.sexp_of_t sexp_of_int h)

Plus, thanks to dead-code-elimination, the size of JavaScript
generated by js_of_ocaml becomes reasonable and js_of_ocaml finishes
the job quickly.  Here is a comparison.

core_kernel:

    $ ocamlfind ocamlc -package core_kernel -linkpkg a.ml
    $ time js_of_ocaml +weak.js core_kernel_runtime.js a.out
    ...
    js_of_ocaml +weak.js core_kernel_runtime.js a.out  8.47s user 0.18s system 99% cpu 8.650 total
    $ wc -c a.js
    855567 a.js

core_kernel_js:

    $ ocamlfind ocamlc -package core_kernel_js -linkpkg a.ml
    $ time js_of_ocaml +weak.js core_kernel_runtime.js a.out
    ...
    js_of_ocaml +weak.js core_kernel_runtime.js a.out  3.41s user 0.07s system 99% cpu 3.492 total
    $ wc -c a.js
    303229 a.js

## Request

It might be good if core_kernel has a compilation flag (something like
`PREFER_THIRTYTWO_WORD_SIZE`) that tells compiler that users prefer
32bit word size even on 64bit architecture.  This may encourage people
to adopt core_kernel for web-browser-based applications.

It must be great if pa_ounit and pa_bench have a compile-time/runtime
control flag that controls the generation of unit tests and benchmark
code.  This may convince people that the adoption of core_kernel is
reasonable.

**Comment by dorafmon** [comment]
@m2ym  Hi, what if I am using ``ocamlbuild'' instead of ``ocamlfind'', how can I pass the js file to js_of_ocaml? Thx!

**Comment by m2ym** [comment]
I don't know much about ocamlbuild.
