### ISSUE TITLE
Documentation/implementation mismatch for List.exists2_exn etc.

### ISSUE THREAD

**Issue by yallop** [janestreet/core_kernel#16]
I've been migrating some list-processing code to use [Core_kernel](https://github.com/janestreet/core_kernel) instead of the [standard library](https://github.com/ocaml/ocaml/tree/trunk/stdlib) and noticed that the documentation strings for the two libraries have somehow become interchanged.  The standard library documentation for `List.exists2` [says](https://github.com/ocaml/ocaml/blob/68fe1eb/stdlib/list.mli#L160-L163):

>  Same as `List.exists`, but for a two-argument predicate. Raise `Invalid_argument` if the two lists have different lengths.

In fact, `List.exists2` does not always raise `Invalid_argument` if the two lists have different lengths:

``` ocaml
# List.exists2 (>) [1; 2] [3; 1; 0];;
- : bool = true
```

On the other hand, the documentation for `Core.Std.List.exists2_exn` [says](https://github.com/janestreet/core_kernel/blob/c1dcec751/lib/core_list.mli#L73-L76):

> Same as `List.exists`, but for a two-argument predicate. Raise `Invalid_argument` if the end of one list is reached before the end of the other.

In fact, `Core.Std.List.exists2_exn` can fail even if the predicate is satisfied (which should mean that the ends of the lists are not reached):

``` ocaml
# Core_kernel.Std.List.exists2_exn ~f:(>) [1; 2] [3; 1; 0];; 
Exception: Invalid_argument "length mismatch in exists2_exn: 2 <> 3 ".
```

I'd submit a pull request fixing the documentation (as for the [standard library](https://github.com/ocaml/ocaml/pull/87)), but wonder if the implementation might be changed instead.  It seems a bit inefficient to [traverse both](https://github.com/janestreet/core_kernel/blob/5aa53ff0/lib/core_list.ml#L236-L237) lists [before starting](https://github.com/janestreet/core_kernel/blob/5aa53ff0/lib/core_list.ml#L274) when the function is [supposed to be short-circuiting](https://github.com/janestreet/core_kernel/blob/5aa53ff/lib/container.ml#L145).

**Comment by bcc32** [comment]
I think for the sake of consistency with the other `List.foo2_exn` functions, we would rather have these functions raise in the case of mismatched lengths.  Regardless, I believe the documentation now reflects the situation accurately:

```ocaml
(** Like {!List.exists}, but for a two-argument predicate.  The exn version will raise if
    the two lists have different lengths. *)
val exists2_exn : 'a t -> 'b t -> f:('a -> 'b -> bool) -> bool
```

Sorry this issue took so long to address!
