### ISSUE TITLE
List.nth_exn documentation/implementation mismatch.

### ISSUE THREAD

**Issue by yallop** [janestreet/core_kernel#17]
The documentation [says][doc]:

> Raise [Failure "nth"] if the list is too short.

but the implementation raises `Invalid_argument`, not `Failure`:

```ocaml
# Core_kernel.Std.List.nth_exn [1] 2;;
Exception: Invalid_argument "List.nth_exn 2 called on list of length 1".
```

The documentation about negative arguments is wrong as well; it says

> Raise [Invalid_argument "List.nth"] if [n] is negative.

but the actual argument to `Invalid_argument` is more descriptive:

```ocaml
# Core_kernel.Std.List.nth_exn [1] (-1);;
Exception: Invalid_argument "List.nth_exn -1 called on list of length 1".
```
[doc]: https://github.com/janestreet/core_kernel/blob/c1dcec7516/lib/core_list.mli#L19-L22

**Comment by bmillwood** [comment]
The documentation now says "Raise if the list [...]"
