### ISSUE TITLE
Argument lists for many functions are wrong in the List documentation

### ISSUE THREAD

**Issue by yallop** [janestreet/core_kernel#18]
For example, the [documentation for List.iter2_exn][iter2-doc] says:

> `List.iter2_exn f [a1; ...; an] [b1; ...; bn]` calls in turn `[f a1 b1; ...; f an bn]`.

whereas the implementation has the argument labeled (or last), not first.

[iter2-doc]: https://github.com/janestreet/core_kernel/blob/c1dcec7516f3e08bd34d6fd2b4193cc677f0af04/lib/core_list.mli#L47-L50

**Comment by bmillwood** [comment]
I believe this has been fixed.
