### ISSUE TITLE
Core_kernel still has some Unix references lurking

### ISSUE THREAD

**Issue by avsm** [janestreet/core_kernel#21]
Notably:

```
lib/pooled_hashtbl.ml:      let unix_time_before = Unix.time () in
```

This forces the pack to depend on Unix even if only Core_kernel is linked.  Most of the other references are just type-level (Unix.file_descr) and less bad since they dont introduce a cma/x dependency.

**Comment by raboof** [comment]
Unfortunately this only lasted until 112.24.00 where `Time_ns` was introduced which calls `Unix.localtime` at some point. See #42

**Comment by yminsky** [comment]
Hmm.  Seems like we need something internal in our build that prevents this from creeping back in.

**Comment by raboof** [comment]
Agreed! I wonder if it'd help to try and convince oasis to use '-dontlink unix' when building the tests?

**Comment by hhugo** [comment]
We do have some internal check now. Wait for the next release.

`async_kernel`, `bin_prot`, `core_kernel`, `fieldslib`, `sexplib`, `typerep_lib`, `variantslib`
should all be free from `Unix`, `Thread`, `Str` references

**Comment by yminsky** [comment]
Lovely!  Thanks.

**Comment by avsm** [comment]
Thanks Hugo!

**Comment by samoht** [comment]
great!
