### ISSUE TITLE
Int32.of_int variant without range check

### ISSUE THREAD

**Issue by ghost** [janestreet/core_kernel#27]
Int32.of_int versions(option and exn) currently perform range check. Can the stdlib of_int be provided as unsafe_of_int for convenience without having to do local open? The range check really hits performance.

**Comment by hhugo** [comment]
We are adding `Int32.of_int_trunc`.  It will be available on github shortly

**Comment by trefis** [comment]
Fixed by https://github.com/janestreet/base/commit/cb63dca921dfc86b5bf46035a8a0a5e566f77589 .
