### ISSUE TITLE
List.init and side effects

### ISSUE THREAD

**Issue by mmottl** [janestreet/core_kernel#38]
`List.init` initializes lists in the opposite order of `Array.init`, i.e. it will call the passed function `f` with the highest number first.  It would be nice to have the same order, but I don't have a problem with the current implementation per se.  Using the "correct" order would either require reversing the result or unsafe list construction.  But I think the initialization order should at least be documented so that users won't be surprised if their `f` depends on the order of side effects.

**Comment by Nick-Chapman** [comment]
Thank you. The reverse order has been documented.
