### ISSUE TITLE
Use result package

### ISSUE THREAD

**Issue by seliopou** [janestreet/core_kernel#48]
Are there any plans for core_kernel to use the result package as a dependency? As I gather most people do, I have a result type floating around in my libraries and I've slowly begun transitioning them to use the result package as a dependency. Having core and async use the same type would make life in a pre-4.03 world much easier.

**Comment by diml** [comment]
Ah, Indeed. We should do this ASAP

**Comment by seliopou** [comment]
It seems as though this has yet to be done. Can we expect this in the next release?

**Comment by diml** [comment]
Thanks for the reminder, I did the change internally, it should be part of the next release

**Comment by seliopou** [comment]
Fixed in 3eab24b47fd8f48a2e68808fb7062774d92e6c9d. Oh happy day!
