### ISSUE TITLE
install core_kernel.mli in opam

### ISSUE THREAD

**Issue by ivg** [janestreet/core_kernel#51]
At some point of time you stopped to install `mli` files at all. 
First of all, many people use `mli` files as a documentation. Second, `merlin` uses it to show documentation, for example `C-c C-l` on `List.filter` results in an error:

```
if: 'List.filter' seems to originate from 'Core_list' whose MLI file could not be found
```

**Comment by diml** [comment]
Ah, it's probably in the latest release. We'll fix that in the next release. For merlin I though the `cmt` and `cmti` were enough. Note that we have [usable html docs now](https://ocaml.janestreet.com/ocaml-core/latest/doc/). The latter should be easier to navigate around than our mli files

**Comment by trefis** [comment]
To get the documentation the `.cmti` should be enough, but that requires calling `M-x merlin-document`. `C-c C-l` calls `merlin-locate` which will indeed need the source files.

**Comment by hhugo** [comment]
mli files are now installed.
