### ISSUE TITLE
can't the compilation of the opam package be parallelized ?

### ISSUE THREAD

**Issue by UnixJunkie** [janestreet/core_kernel#52]
installing core_kernel from sources via opam takes really too long.

**Comment by diml** [comment]
how long is too long?

**Comment by UnixJunkie** [comment]
This is subjective, I agree. However, when there are several core available, that's a shame to not use them.

**Comment by diml** [comment]
Ah, well that's an ocamlbuild issue I guess...

**Comment by UnixJunkie** [comment]
Don't you have Jenga at janestreet to super parallelize a build ? I see another problem: maybe opam needs to know that a package can build in parallel otherwise it might overload the computer; trying to install other packages in parallel.

**Comment by agarwal** [comment]
Correct solution is to have your build commands use OPAM's `jobs` variable, which end users have control over (by setting it in their `.opam/config` file, or setting the `OPAMJOBS` environment variable). I don't see this being passed to either the `configure` nor the `make` command. The solution might be as simple as doing `make -j %{jobs%}`, but I don't know oasis. Maybe there's some other way you're supposed to tell oasis about this.

**Comment by diml** [comment]
Well, we are thinking of changing the build of our packages to something jenga-based, but it's not ready yet. However it's still not going to be as fast as our internal build; we build everything at once with the same jenga instance, while opam installs packages one by one

**Comment by UnixJunkie** [comment]
Anything that parallelizes the build of core_kernel would be an improvement to me.

**Comment by UnixJunkie** [comment]
@agarwal if we use the jobs variable in the build instructions, would opam know that it should not compile other packages in parallel to the one being built (because the one being built is building in parallel)? I doubt it.

**Comment by agarwal** [comment]
@UnixJunkie So are you concerned about overloading your processors? Say package A and B could both be built in parallel. If you set `jobs = 2`, I guess OPAM will do so, using both your cores. But then A's and B's own build rules also try to use 2 cores each, so hopefully you actually have 4 cores. I'm sure OPAM wouldn't know about this because the build rules of a package are not understood by OPAM.

This is actually why I don't care much about Core's build times. Whenever I initialize a new switch or do an `opam upgrade`, I'm anyway installing tens of packages. There's plenty of parallelism already.

**Comment by UnixJunkie** [comment]
@agarwal recently I was testing for the latest core version that would allow a package to compile; the package was missing a version constraint on core. That was quite a slow and boring process. Hopefully, I will not have to do this everyday.

**Comment by UnixJunkie** [comment]
@agarwal I remember you could live fine with the install times of GODI packages when GODI was the way to go before OPAM. I was never satisfied with them. :)

**Comment by agarwal** [comment]
Indeed, I'm clearly not so sensitive to this issue!

**Comment by hhugo** [comment]
Solved by jbuilder/dune
