### ISSUE TITLE
Nested Let_syntax module

### ISSUE THREAD

**Issue by jfeser** [janestreet/core_kernel#53]
Should these modules be nested?

https://github.com/janestreet/core_kernel/blob/master/src/or_error.ml#L45

My code using Let_syntax now looks like this:

```
let module Let_syntax = Or_error.Let_syntax.Let_syntax in
let%bind ...
```
Is this the intended usage?

**Comment by trefis** [comment]
The idea is to write:
```ocaml
let open Or_error.Let_syntax in
let%bind ...
```

**Comment by jfeser** [comment]
I see. That makes sense. Thanks!
