### ISSUE TITLE
weird behavior of the result type

### ISSUE THREAD

**Issue by ivg** [janestreet/core_kernel#54]
After moving to the new result type I have a strange behavior. Looks like the trick with `namespace_wrappers` confused the typechecker:

The following program typechecks:

``` ocaml
    type ('a,'b) result = ('a,'b) Result.result = Ok of 'a | Error of 'b
    type ab = [`a | `b]
    type abc = [ab| `c]
    let a : ab = `a
    let x = Error a
    let _ = (x :> ('a,abc) result)
```

But, if I will use core_kernel 113.33.01, then the program doesn't typecheck:

``` ocaml
    open Core_kernel.Std

    type ab = [`a | `b]
    type abc = [ab| `c]

    let a : ab = `a

    let x = Error a

    let _ = (x :> ('a,abc) Result.t)
```

With the following error:

```
ocamlfind c -package core_kernel abc.ml
File "abc.ml", line 10, characters 9-10:
Error: This expression cannot be coerced to type
         ('a, abc) Core_kernel.Std.Result.t =
           ('a, abc) Result_lib.Result.result;
       it has type
         ('a, ab) Core_kernel.Std._result = ('a, ab) Result_lib.Result.result
       but is here used with type
         ('a, abc) Core_kernel.Std.Result.t =
           ('a, abc) Result_lib.Result.result
       Type ab = [ `a | `b ] is not compatible with type
         abc = [ `a | `b | `c ] 
       The first variant type does not allow tag(s) `c
```

**Comment by ivg** [comment]
I've pinpointed the problem. The `Result_lib.cmi` file is not installed, so the compiler doesn't know that result is just a normal injective ADT and assumes the worst. So the resolution is to install this `cmi`. I've checked, it works, when I copy `resul_lib.cmi` into the `core_kernel` folder.

**Comment by trefis** [comment]
Thanks for the report!
I'm try to release a new minor version soon.

**Comment by ivg** [comment]
and please, don't forget to include `.mli` files, this is still the best source of documentation ;)

**Comment by diml** [comment]
release 113.33.03 now properly installs `result_lib.cmi`, although I just realized I forgot to include the `.mli` file... this will be for next release

**Comment by diml** [comment]
Acutally currently we are installing none of the `.mli` files, we'll need to update [js-build-tools](https://github.com/janestreet/js-build-tools) to take care of this
