### ISSUE TITLE
Core_kernel.Core_result.t not compatible with the new Pervasives.result

### ISSUE THREAD

**Issue by keleshev** [janestreet/core_kernel#56]
```
utop # #require "result";;
utop # Result.Ok () = Pervasives.Ok ();;
- : bool = true
utop # #require "core_kernel";;
utop # Core_kernel.Core_result.Ok () = Pervasives.Ok ();;
Error: The constructor Pervasives.Ok belongs to the variant type result
       but a constructor was expected belonging to the variant type
         Core_kernel.Core_result.t = Result_lib.Result.result
```

I'm using 4.03.0 with:

```
core_kernel     113.33.01+4.03
result  1.2
```

<details>
 <summary>

4.03.0 switch</summary>

<pre>
base-bigarray   base    root
base-bytes  base    installed
base-threads    base    root
base-unix   base    root
bin_prot    113.33.00+4.03  installed
camomile    0.8.5   installed
conf-m4 1   installed
core_kernel 113.33.01+4.03  root
cppo    1.3.2   installed
fieldslib   113.24.00   installed
lambda-term 1.10    installed
lwt 2.5.2   installed
menhir  20160526    root
ocamlbuild  0.9.2   installed
ocamlfind   1.6.2   installed
ocp-ocamlres    0.3 root
pprint  20140424    installed
ppx_assert  113.33.00   installed
ppx_bench   113.33.00+4.03  installed
ppx_bin_prot    113.33.00+4.03  installed
ppx_compare 113.33.00+4.03  installed
ppx_core    113.33.01+4.03  installed
ppx_custom_printf   113.33.00+4.03  installed
ppx_deriving    3.3 root
ppx_driver  113.33.01+4.03  installed
ppx_enumerate   113.33.00+4.03  installed
ppx_expect  113.33.01+4.03  installed
ppx_fail    113.33.00+4.03  installed
ppx_fields_conv 113.33.00+4.03  installed
ppx_here    113.33.00   installed
ppx_inline_test 113.33.00+4.03  installed
ppx_jane    113.33.00   installed
ppx_let 113.33.00+4.03  root
ppx_optcomp 113.33.00+4.03  installed
ppx_pipebang    113.33.00+4.03  installed
ppx_sexp_conv   113.33.01+4.03  root
ppx_sexp_message    113.33.00+4.03  installed
ppx_sexp_value  113.33.00+4.03  installed
ppx_tools   5.0+4.03.0  installed
ppx_type_conv   113.33.01+4.03  root
ppx_typerep_conv    113.33.00+4.03  installed
ppx_variants_conv   113.33.00+4.03  installed
re  1.6.1   installed
react   1.2.0   installed
result  1.2 installed
sexplib 113.33.00+4.03  installed
typerep 113.24.00   installed
utop    1.19.2  root
variantslib 113.24.00   installed
zed 1.4 installed
</pre>

</details>

**Comment by hhugo** [comment]
This is fixed
