### ISSUE TITLE
When is 114.10+84 going to be released onto OPAM?

### ISSUE THREAD

**Issue by tmcgilchrist** [janestreet/core_kernel#60]
Apologies if this information is available elsewhere.
I'm interested in using the splittable_random functionality in a library.

https://github.com/janestreet/core_kernel/blob/114.04/src/splittable_random.ml

**Comment by diml** [comment]
We are planning to do a new stable release of all our packages in December

**Comment by tmcgilchrist** [comment]
Cheers, I'll take a local copy for now and update when it's released.

**Comment by diml** [comment]
BTW, you can add our [development opam repository](https://github.com/janestreet/opam-repository.git) to get the development versions of all our packages
