### ISSUE TITLE
fails to build with jbuilder error

### ISSUE THREAD

**Issue by agarwal** [janestreet/core_kernel#62]
Latest commit 39d72cf7788fb0d17a99b4d4b26af49f767d2195 fails to build:

```
$ jbuilder build-package core_kernel
File "src/jbuild", line 29, characters 3-14:
Error: Unknown field c_libraries
```

Also, this package and some others have multiple commits with the same comment "114.20+69". Is that simply an error?

**Comment by diml** [comment]
You need to upgrade jbuilder to the latest development version.

For the comment it's because the commits are generated. 114.20+69 correspond to our internal version number. Internally we have a single monolithic repository that we automatically split for the public release.

**Comment by agarwal** [comment]
> You need to upgrade jbuilder to the latest development version.

Right, just tried that and it works. Thanks.

> For the comment it's because the commits are generated. 114.20+69 correspond to our internal version number.

Aren't the messages pseudo-tags indicating a release? So no two messages should indicate the same version number?

**Comment by diml** [comment]
Yh but I often push several time from our same internal release to fix minor issues. In general I try to override the commit message with something more specific but sometime I forget...

**Comment by agarwal** [comment]
Ok gotcha. So I won't pay too much attention to these un-official version numbers. Thanks for the answers. I'll close this issue.
