### ISSUE TITLE
113.33.03 requires OCaml 4.02.3?

### ISSUE THREAD

**Issue by andrenth** [janestreet/core_kernel#64]
Hi

Is this restriction correct? Previous versions are installable in newer OCaml versions.

Cheers,
Andre

**Comment by andrenth** [comment]
```
$ opam upgrade core_kernel --verbose
Everything as up-to-date as possible.
The following newer versions couldn't be installed:
  - core_kernel.113.33.03 is not available because your system doesn't comply
with
    ocaml-version = "4.02.3".
```

**Comment by bmillwood** [comment]
I'm not certain but I expect this was originally intended to be a ≥ constraint.

**Comment by diml** [comment]
It is correct, you should install 113.33.02+4.03 instead for 4.03. The upcoming v0.9.0 is compatible with OCaml >= 4.03
