### ISSUE TITLE
Minor documentation issue with result type

### ISSUE THREAD

**Issue by eriklovlie** [janestreet/core_kernel#68]
The rendered documentation for the result type [0] has some typos:

> 'a is a function's expected return type, and 'b is often an error message string.

The type parameters are not called 'a and 'b though, but 'ok and 'err.

[0] https://ocaml.janestreet.com/ocaml-core/latest/doc/core_kernel/Std/Result.mod/

**Comment by trefis** [comment]
That url is missleading, `latest` is not actually the latest version.
I'm going to update the link, in the meantime you can have a look at [the doc for v0.9](https://ocaml.janestreet.com/ocaml-core/v0.9/doc/)

Btw, seems like the issue you reported was fixed, cf. https://ocaml.janestreet.com/ocaml-core/v0.9/doc/base/Base/Result/index.html

**Comment by trefis** [comment]
Thank you!

**Comment by trefis** [comment]
Finally updated the `latest` url, sorry for the delay and thanks again for the report!

**Comment by eriklovlie** [comment]
Thanks for fixing :)
