### ISSUE TITLE
Provide Base's M functor for collections

### ISSUE THREAD

**Issue by leviroth** [janestreet/core_kernel#72]
In Base, collection modules such as `Set` and `Map` contain a functor `M` which is useful for referring to the type of a collection produced by a comparator:

    type 'a int_map = 'a Map.M(Int).t

However, this doesn't appear to be a part of the Core versions of `Set` and `Map`. It would be nice to have, especially now that Core is going in Base's direction of not requiring a new module for each key type.

**Comment by yminsky** [comment]
I think this is just an omission on our part. I've been running into the same thing as I've been looking at using Base more in RWO. I'll see if we can get this resolved.

**Comment by hhugo** [comment]
This believe this has been fixed
