### ISSUE TITLE
Hash_heap disappeared between v0.11.0 and v0.12.0

### ISSUE THREAD

**Issue by jasone** [janestreet/core_kernel#89]
Perhaps this was intentional, but if so it should be mentioned in `CHANGES.md`, and ideally marked for deprecation prior to removal.

**Comment by yminsky** [comment]
Yeah, sorry, this is lame.  We didn't get a changelog out before pushing the release, which seems like a mistake.

In this case, Hash_heap is still in the public release, it's just been moved to its own toplevel library, as part of our efforts to make Core and Core_kernel more streamlined. You can find it here.

https://github.com/janestreet/core_kernel/tree/master/hash_heap

It's indeed still part of the Core_kernel distribution; you just need to ask for the library separately.

Again, apologies for the lack of changelog.

**Comment by wu-s-john** [comment]
Hi @yminsky , how do you call the `Hash_heap` module for the latest release (v.13.0). Sorry, this isn't clear. I tried using `Core_kernel.Hash_heap`, but the module was undefined. I see that it is in the source of the current release though.

**Comment by bcc32** [comment]
You should use `core_kernel.hash_heap` as the name of the library (for example, in your dune file), but the module is just called `Hash_heap`, and it's not a submodule of `Core_kernel` any more.
