### ISSUE TITLE
exception `Gc.finalise` with OCaml 4.02

### ISSUE THREAD

**Issue by Kakadu** [janestreet/core_kernel#9]
Hi. After installing 4.02 using opam I'm getting strange exception `Invalid_argument Gc.finalise`. I'm using GNU/Linux but I'm not sure is it core_kernel's error or sexplib's one (gdb points on line where  `with sexp` syntax extension is used). Can anybody test it on your machine, please?

Demo project:
`git clone https://github.com/Kakadu/core_kernel_4.02_test`

**Comment by diml** [comment]
FIxed since sexplib 111.25.00
