### ISSUE TITLE
provide support for deriving bin_io for applicative types

### ISSUE THREAD

**Issue by ivg** [janestreet/core_kernel#90]
While it is possible to derive sexp and compare interfaces for a type specified by an applicative functor `M`, e.g., the following works fine (since 0.12)

```ocaml
type test = Set.M(String).t [@@deriving compare, sexp]
```

it looks like, the corresponding support for Bin_prot is not yet implemented,

```ocaml
# type test = Set.M(String).t [@@deriving bin_io] ;;
Error: Unbound value Set.bin_shape_m__t
```

Without this feature, we have to fall back to the old `X.Set.t` notation, which bloats the interface, increasing compilation time, confusion, and, basically, renders the excellent `M(X).t` approach useless (well at least for us, since we want to have most of our types to be serializable).

**Comment by yminsky** [comment]
We just implemented an internal fix for this. Should hit the public release in the next week or so.
