### ISSUE TITLE
Useful operations missing in Core_kernel.Map: find_first_opt find_last_opt

### ISSUE THREAD

**Issue by tomjridge** [janestreet/core_kernel#94]
Hi,

In the standard library, they have useful operations such as: find_first_opt and find_last_opt. These take a "monotonic increasing" predicate and efficiently locate a particular binding.

Are there any plans to introduce them to Base/Core_kernel? 

Is there an efficient way to implement them using existing operations?

Thanks

**Comment by yminsky** [comment]
CC'ing @ceastlund @bcc32 

I don't think there's an efficient way of implementing it from the existing API, and I don't think it exists, nor do I know of any plans to add it.  I suspect a PR to base with an implementation would be welcomed, though. It certainly seems like a reasonable primitive to add. (Thought I'd defer to the Base maintainers on that.)

**Comment by bcc32** [comment]
I think the closest thing, which would only apply to specific cases, would be `closest_key` or `to_sequence`.  But I agree that these seem pretty useful, both for Map and Set.

**Comment by bcc32** [comment]
`{Map,Set}.binary_search{,_segmented}` are part of the latest GitHub release of [base](https://github.com/janestreet/base/commit/866a521a21cb87218520ec50dd58d47bb8ff151e) and [core_kernel](https://github.com/janestreet/core_kernel/commit/6eac56d9c59210009aa3767d08287114d9bab0d3).

**Comment by tomjridge** [comment]
@bcc32 Thanks! Much appreciated.

**Comment by bcc32** [comment]
Closing.  The new functions will appear in the next opam release :)
