### ISSUE TITLE
bigstring and bin_io deriving 

### ISSUE THREAD

**Issue by gitoleg** [janestreet/core_kernel#97]
Hey,
May I ask you what happened with `Bigstring.t [@@deriving bio_io]`?
Was it dropped intentionally?
What can we use instead?

thanks!

**Comment by bcc32** [comment]
The functionality was moved to the `Bigstring.Stable.V1` module (see also this [forum post](https://discuss.ocaml.org/t/ann-v0-12-release-of-jane-street-packages/3499/6?u=bcc32)):

>You now have to pick between Bigstring.Unstable.t and Bigstring.Stable.V1.t.
>
> This is so that your programs don’t break when there is a change to the serialization format, unless you ask for it by picking “unstable”.
