### ISSUE TITLE
Tuple.T2 does not contain documented map function

### ISSUE THREAD

**Issue by Bladtman242** [janestreet/core_kernel#98]
I don't know if this is the right place for this issue, but since I don't know where else to report it:
The [documentation](https://ocaml.janestreet.com/ocaml-core/latest/doc/core_kernel/Core_kernel/Tuple/T2/index.html) reports the Tuple.T2.map function that is in the code, however, the version of the code hosted on ocaml.janestreet.com (and provided by opam) does not seem to include it.

**Comment by bcc32** [comment]
I think this might be a bug with how the documentation is generated.  `Tuple.T2.map` was added after v0.13 of core_kernel was released, so it is not available in opam.

However, the documentation site claims to be showing the v0.13 version but appears to be showing the master branch version, so I think something went wrong there.

**Comment by Bladtman242** [comment]
@bcc32 Thanks.
I'm not really sure who to contact about that. Do you know?

**Comment by bcc32** [comment]
I've reported the issue internally to the list responsible for the public release process.  I'll follow up when we find out what the issue is.

**Comment by Bladtman242** [comment]
Thank you.

**Comment by bcc32** [comment]
Looks like the version we generated the documentation with didn't match the version in opam, and the `map` function was introduced in between.  Now that v0.14 has been released, and the website has been updated, I believe the documentation should be in line with the code in opam now.
